name: multiegg-arm64

on:
  workflow_dispatch:

jobs:
  push:
    name: "multiegg:java17"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PUSH_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./multiegg-java17
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/ademersln/exagear:java17
