name: build mta
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - yolks/mta/**
jobs:
  push:
    name: "yolks:${{ matrix.build }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build:
          - mta
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          version: "v0.8.2"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PUSH_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./yolks/${{ matrix.build }}
          file: ./yolks/${{ matrix.build }}/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ghcr.io/ademersln/yolks:${{ matrix.build }}
